name: Flask App CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    name: Test Flask Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-cors firebase-admin google-cloud-firestore

    - name: Run Tests
      run: |
        flask --app service.py run --host=127.0.0.1 --port=5000 &
        sleep 5
        curl -X GET http://127.0.0.1:5000/menu
